services:
  web:
    build: .
    ports:
      - "8000:8000"  # ホストの8000ポートをコンテナの8000ポートにマッピング
    volumes:
      - .:/app  # ホストの現在のディレクトリをコンテナの/appにマウント
    environment:
      - DB_ENGINE=django.db.backends.sqlite3  # SQLite3を使用する設定
      - DB_NAME=/app/db.sqlite3  # SQLiteのデータベースファイルのパス