# Generated by Django 5.1.2 on 2024-10-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_user_is_active_user_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_superuser',
        ),
    ]
